In [1]:
import numpy as np
from asoh.models.base import *

Demonstrate InputQuantities class with single values per variable

In [2]:
time = 0.
current = 0.
input_vector = InputQuantities(time = time, current = current)
input_vector.to_numpy()


array([[0., 0.]])

Demonstrate InputQuantities class with arrays

In [3]:
time = np.arange(10)
current = 2.5 * np.hstack((np.ones(5), -np.ones(5)))
temperature = 25 + 5 * np.random.rand(10)
input_vector = InputQuantities(time = time, 
                               current = current, 
                               temperature = temperature                               )
input_vector.to_numpy()

array([[ 0.        ,  2.5       , 29.68359434],
       [ 1.        ,  2.5       , 28.85920392],
       [ 2.        ,  2.5       , 28.59258081],
       [ 3.        ,  2.5       , 29.82035499],
       [ 4.        ,  2.5       , 28.83393329],
       [ 5.        , -2.5       , 28.19072296],
       [ 6.        , -2.5       , 28.53667808],
       [ 7.        , -2.5       , 29.51457025],
       [ 8.        , -2.5       , 26.11021682],
       [ 9.        , -2.5       , 27.59891573]])

Demonstrate OutputMeasurements

In [7]:
volts = np.hstack((np.linspace(3,4,5), np.linspace(4,3,5)))
output = OutputMeasurements(terminal_voltage = volts)
output.to_numpy()

array([3.  , 3.25, 3.5 , 3.75, 4.  , 4.  , 3.75, 3.5 , 3.25, 3.  ])